config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  namespace :api do
    post 'checks', to: 'webhooks#github'
  end

  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#destroy'

    root 'home#show'

    resources :repositories, only: %i[index new create show] do
      scope module: :repositories do
        resources :checks, only: %i[show create]
      end
    end
  end
end

app/views/layouts/shared/_flash.html.slim
- flash.any?
  .container.my-2
    - flash.each do |key, value|
      div[class="alert #{flash_class(key)} alert-dismissible fade show" role="alert"]
        = value
        button.btn-close[type="button" data-bs-dismiss="alert" aria-label="Close"]

app/views/layouts/shared/_footer.html.slim
footer[class="footer fixed-bottom bg-dark text-light mt-auto"]
  .container-xl
    .row.py-2 © qsimpleq, #{Time.zone.today.year}

app/views/layouts/shared/_header.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      a.navbar-brand.me-md-4 href = root_path
        = image_tag('hexlet_logo.jpg', width: 30)
      .collapse.navbar-collapse[id="navbarToggler"]
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          li.nav-item.me-2 = link_to t('.home'), root_path, class: 'nav-link text-dark'
          - if signed_in?
            li.nav-item.me-2 = link_to t('.repositories'), repositories_path, class: 'nav-link text-dark'
    ul.nav.nav-pills
      - if signed_in?
        li.nav-item
          span.nav-link.text-secondary = current_user.email
        li.nav-item
          = button_to t('action.sign_out'), auth_logout_path, method: :delete, class: 'nav-link text-dark', data: { turbo: 'false' }
      - else
        li.nav-item
          = button_to auth_request_path(:github), method: :post, class: 'nav-link text-dark', data: { turbo: 'false' } do
            = t('action.sign_in')