config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  namespace :api do
    post 'checks', to: 'webhooks#github'
  end

  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#destroy'

    root 'home#show'

    resources :repositories, only: %i[index new create show] do
      scope module: :repositories do
        resources :checks, only: %i[show create]
      end
    end
  end
end

app/models/repository.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repositories
#
#  id              :integer          not null, primary key
#  full_name       :string
#  git_url         :string
#  language        :string
#  name            :string
#  repo_created_at :datetime
#  repo_updated_at :datetime
#  ssh_url         :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  github_id       :integer
#  user_id         :integer
#
# Indexes
#
#  index_repositories_on_user_id  (user_id)
#
class Repository < ApplicationRecord
  extend Enumerize

  belongs_to :user, inverse_of: :repositories
  has_many :checks, dependent: :destroy

  validates :github_id, presence: true

  enumerize :language,
            default: :javascript,
            in: %i[javascript ruby]

  def user_directory
    Rails.root.join("tmp/repositories/#{user.nickname}")
  end

  def directory
    Rails.root.join("#{user_directory}/#{name}")
  end

  def url
    "#{ENV.fetch('USER_PROVIDER_URL', 'https://github.com')}/#{full_name}"
  end
end

app/models/repository/check.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repository_checks
#
#  id            :integer          not null, primary key
#  aasm_state    :string           default("created"), not null
#  check_result  :json
#  offense_count :integer
#  passed        :boolean          default(FALSE)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  commit_id     :string
#  repository_id :integer          not null
#
# Indexes
#
#  index_repository_checks_on_aasm_state     (aasm_state)
#  index_repository_checks_on_repository_id  (repository_id)
#
# Foreign Keys
#
#  repository_id  (repository_id => repositories.id)
#
class Repository
  class Check < ApplicationRecord
    include AASM

    belongs_to :repository, inverse_of: :checks

    aasm do
      state :created, initial: true
      state :checking, :finished, :failed

      event :run_check do
        transitions from: :created, to: :checking
      end

      event :mark_as_finish do
        transitions from: :checking, to: :finished
      end

      event :mark_as_fail do
        transitions from: :checking, to: :failed
      end
    end
  end
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ApplicationController < Web::ApplicationController
    end
  end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ChecksController < Web::Repositories::ApplicationController
      before_action :authenticate_user!
      before_action :set_repository

      def show
        authorize @repository

        @check = @repository.checks.find(params[:id])
        @check_result = @check.check_result.nil? ? nil : JSON.parse(@check.check_result, symbolize_names: true)
      end

      def create
        authorize @repository

        if @repository.checks&.last&.checking?
          return redirect_to repository_path(@repository), alert: t('.last_in_process')
        end

        ApplicationContainer[:repository_check_job].perform_later(@repository)
        redirect_to repository_path(@repository), notice: t('.check_started')
      end

      private

      def set_repository
        @repository = current_user.repositories.find(params[:repository_id])
      end
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

module Web
  class RepositoriesController < Web::ApplicationController
    before_action :authenticate_user!

    def index
      authorize Repository

      @repositories = current_user.repositories.order(name: :asc).page(params[:page])
    end

    def show
      @repository = current_user.repositories.find(params[:id])
      authorize @repository
    end

    def new
      @repository = Repository.new
      authorize @repository

      @available_repositories = select_available_repos(cached_fetch_repos)
    end

    def create
      @repository = current_user.repositories.find_or_initialize_by(repository_params)
      @repository.name ||= '-'
      @repository.full_name ||= '-'
      authorize @repository

      if @repository.save
        Rails.cache.delete(user_repos)
        RepositoryUpdateJob.perform_later(@repository)
        redirect_to repositories_path, notice: t('.success')
      else
        redirect_to new_repository_path, alert: t('.error')
      end
    end

    private

    def repository_params
      params.require(:repository).permit(:github_id)
    end

    def user_repos
      "user_repositories_#{current_user.id}"
    end

    def fetch_repos
      fetch_repositories = ApplicationContainer[:fetch_repositories_service].new(current_user)
      fetch_repositories.perform
      fetch_repositories.repositories
    end

    def cached_fetch_repos
      repos = nil
      repos_json = Rails.cache.fetch(user_repos, expires_in: ApplicationContainer[:USER_REPOSITORIES_EXPIRE]) do
        repos = fetch_repos
        JSON.generate(repos)
      end

      return JSON.parse(repos_json, symbolize_names: true) unless repos

      repos
    end

    def select_available_repos(repos)
      exists_repos = Repository.where(user_id: current_user.id).pluck(:github_id).flatten
      repos.reject { exists_repos.include?(_1[:id]) }
    end
  end
end

app/helpers/web/repositories_helper.rb
# frozen_string_literal: true

module Web
  module RepositoriesHelper
  end
end

app/views/web/repositories/index.html.slim
.mb-4.mt-4
  = link_to t('.add'), new_repository_path, class: 'btn btn-primary'
  table.table.table-striped.table-hover.mt-4
    thead
      th[scope="col"] = t('.name')
      th[scope="col"] = t('.language')
      th[scope="col"] = t('.last_check_status')
    tbody
      - @repositories.each do |repository|
        tr
          td = link_to repository.name, repository_path(repository)
          td = repository.language
          td = repository.checks.any? ? (repository.checks.last.passed || false) : t('.not_started')
  = paginate @repositories

app/views/web/repositories/new.html.slim
.mb-4.mt-4
  = simple_form_for(@repository) do |f|
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

    = f.input :github_id, as: :select,
            label: t('.title'),
            required: true,
            disabled: @available_repositories.empty?,
            collection: @available_repositories.sort_by { |a| a[:full_name] } \
                                               .map { [_1[:full_name], _1[:id]] }
    - if @available_repositories.empty?
      .form-text.mb-3 = t('.all_added')
    = f.button :submit, t('.submit'), class: 'btn-success', disabled: @available_repositories.empty?

app/views/web/repositories/show.html.slim
.mb-4
  h1 = @repository.full_name
= link_to t('.check'), repository_checks_path(@repository),
                       class: "btn btn-primary mb-4#{@repository.checks&.last&.checking? ? ' disabled' : ''}",
                       data: { turbo_method: :post }
p
  strong.me-2 = t('.name')
  = "#{current_user.nickname}/#{@repository.name}"
p
  strong.me-2 = t('.language')
  = @repository.language
p
  strong.me-2 = t('.created_at')
  = I18n.l(@repository.created_at, format: :default)
p
  strong.me-2 = t('.updated_at')
  = I18n.l(@repository.updated_at, format: :default)

hr

- if @repository.checks.any?
  table.table.table-striped
    thead
      th[scope="col"]
      th[scope="col"] = t('.state')
      th[scope="col"] = t('.commit_id')
      th[scope="col"] = t('.passed')
      th[scope="col"] = t('.created_at')
    tbody
      - @repository.checks.order(id: :desc).each do |check|
        tr
          td = link_to check.id, repository_check_path(@repository.id, check.id)
          td = t("activerecord.attributes.check.states.#{check.aasm_state}")
          td
            - if check.commit_id
              = link_to check.commit_id, "#{@repository.url}/commit/#{check.commit_id}"
            - else
              | -
          td = check.passed
          td = I18n.l(check.created_at, format: :short)